version: '3.8'
services:
  frontend:
    container_name: project_name
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
